### ISSUE TITLE
Is there support to mount the SDcard on the Robin E3 through USB?

### ISSUE THREAD

**Issue by hieppo** [makerbase-mks/MKS-Robin-E3-E3D#50]
I connect the Robin E3 to a Pi and been trying to mount the SDcard on the E3. However, I do not see any device listed. Is the Marlin firmware has support for this feature? Is there a Smoothieware for this board?

**Comment by mks-viva** [comment]
Hi! I am very sorry, the current MKS Robin E3 motherboard does not support this function, mainly because the Robin E3 motherboard uses the serial port chip instead of directly using the STM32 virtual serial port function.
![image](https://user-images.githubusercontent.com/16629551/101229616-13edf900-36dc-11eb-9f60-b3eb557a64c3.png)

**Comment by hieppo** [comment]
Hmm, disappointed but thanks for the information. I guess I have to pop the sdcard out  each to flash. Is there a flash method using usb?

**Comment by mks-viva** [comment]
USB is currently only used to connect to the host computer and cannot perform other functions.

**Comment by mks-viva** [comment]
We will improve it in the next version, so stay tuned. I will close this issues
